(defun dani ()
  (interactive)
  (color-theme-install
   '(color-theme-dani
      ((background-color . "#000000")
      (background-mode . light)
      (border-color . "#000000")
      (cursor-color . "#729ecb")
      (foreground-color . "#ffffff")
      (mouse-color . "black"))
     (fringe ((t (:background "#000000"))))
     (mode-line ((t (:foreground "#eeeeec" :background "#262626"))))
     (region ((t (:background "#083512"))))
     (font-lock-builtin-face ((t (:foreground "#729dcb"))))
     (font-lock-comment-face ((t (:foreground "#aaaaaa"))))
     (font-lock-function-name-face ((t (:foreground "#ffd100"))))
     (font-lock-keyword-face ((t (:foreground "#e3871c"))))
     (font-lock-string-face ((t (:foreground "#70b607"))))
     (font-lock-type-face ((t (:foreground"#da4939"))))
     (font-lock-constant-face ((t (:foreground "#eeeeec"))))
     (font-lock-variable-name-face ((t (:foreground "#eeeeec"))))
     (minibuffer-prompt ((t (:foreground "#729fcf" :bold t))))
     (font-lock-warning-face ((t (:foreground "red" :bold t))))
     )))
(provide 'dani)
(deftheme dani "Railscasts based theme")
(provide-theme 'dani)
